#baseURL = "http://192.168.0.20:1313"
#baseURL = "https://readmehong.github.io"
#languageCode = "en-us"

baseurl = "/"
title = "READMEHONG BLOG"
theme = "mainroad"
languageCode = "UTF-8"
paginate = "10"
disqusShortname = "comments by entering disqus shortname???"
googleAnalytics = "UA-127985349-1"

[Author]
 name = "readmehong"
 bio = "readmehong@gmail.com"
 avatar = "img/avatar.png"

[Params]
 subtitle = '##'
 description = 'param description'
 opengraph = true
 twitter_cards = true
 readmore = false
 authorbox = true
 postSections = ["post"]

[Params.sidebar]
 home = "right"
 list = "right"
 single = "right"
 widgets = ["search", "recent", "categories", "taglist"]

[params.widgets]
 recent_num = 5
 tags_counter = false
